name: Test
on:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Deno
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh
    - name: Test
      run: |
        /home/runner/.deno/bin/deno test
